# load docker hub image....
FROM python

# copy the root app to docker app....
COPY api_app /app

# set app as working dir....
WORKDIR /app

# install packages in build of image....
RUN pip install -r requirements.txt 

# set port for image....
EXPOSE 5000

# call python as command....
ENTRYPOINT [ "python" ] 

# run main.py....
CMD [ "main.py" ] 
